# Numpy Solutions

## Q1
Create 4x6 array of floats between 3.5 and 5.5.  Display the results to 3 decimal 
places using `set_printoptions`.

In [20]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

a = np.random.random(size=(4,6))
print(a*2+3.5)

[[4.762 4.195 4.188 3.783 4.352 4.031]
 [5.458 4.098 5.462 3.504 4.406 5.051]
 [4.305 3.608 4.373 4.129 5.247 3.905]
 [5.309 3.775 4.904 4.420 3.869 4.839]]


## Q2
Create a 4x6 array of random ints between 10 and 100.

In [21]:
import numpy as np

a = np.random.randint(low=10, high=100, size=(4,6))
print(a)

[[92 44 86 21 63 33]
 [24 15 55 36 80 96]
 [16 21 13 91 52 14]
 [20 32 79 72 10 72]]


## Q3
Create another 4x6 array of random ints between 10 and 100.  Then set all the even
numbers to 100.

In [49]:
import numpy as np

a = np.random.randint(low=10, high=100, size=(4,6))
print(f"array BEFORE setting even numbers:")
print(a)
a[a%2==0] = 100
print(f"array AFTER setting even numbers:")
print(a)

array BEFORE setting even numbers:
[[13 49 83 35 30 93]
 [31 37 87 62 89 13]
 [31 68 24 30 60 59]
 [40 90 79 48 48 20]]
array AFTER setting even numbers:
[[ 13  49  83  35 100  93]
 [ 31  37  87 100  89  13]
 [ 31 100 100 100 100  59]
 [100 100  79 100 100 100]]


## Q4
Create another 4x6 array of random ints between 10 and 100.  Create a new 1D array
with all the numbers in the first array that are less than 50.

In [23]:
import numpy as np

a = np.random.randint(low=10, high=100, size=(4,6))
print(a)
b = a[a[:] < 50]
print(b)

[[76 64 44 39 14 80]
 [97 52 14 93 45 80]
 [53 57 97 71 75 73]
 [84 25 64 45 39 93]]
[44 39 14 14 45 25 45 39]


## Q5
Create a 4x6 array of random integers between 10 and 100.
Create a new 4x3 array of the lowest 50% of the original array whilst 
preserving order.

In [24]:
import numpy as np

a = np.random.randint(low=10, high=100, size=(4,6))
print(a)
a = a[a <= np.percentile(a, 50)]
print(a.reshape((4,3)))

[[74 80 78 74 16 27]
 [89 12 79 73 70 17]
 [57 14 48 30 74 13]
 [25 87 94 90 16 59]]
[[16 27 12]
 [17 57 14]
 [48 30 13]
 [25 16 59]]


## Q6
Create a 4x6 array of random integers between 10 and 100.
Set the lowest 50% of the array to 0.

In [25]:
import numpy as np

a = np.random.randint(low=10, high=100, size=(4,6))
print(a)
a[a <= np.percentile(a, 50)] = 0
print(a)

[[48 15 67 30 13 71]
 [10 32 89 64 93 32]
 [77 80 67 85 26 49]
 [28 22 27 64 74 52]]
[[ 0  0 67  0  0 71]
 [ 0  0 89 64 93  0]
 [77 80 67 85  0  0]
 [ 0  0  0 64 74 52]]


## Q7
Create a 6x4 array of ints where the first row is filled
with 10, the second with 11, the third with 12 and the last with 13.

In [31]:
import numpy as np

a = np.arange(10, 14)
b = np.repeat(a, 6)
b = b.reshape((4,6))
print(b)

[[10 10 10 10 10 10]
 [11 11 11 11 11 11]
 [12 12 12 12 12 12]
 [13 13 13 13 13 13]]


## Q8
Create a 8x5 array of ints using the "tile" method so that each successive row is rotated left.  The solution should look like:

    [[10 11 12 13 10]
     [11 12 13 10 11]
     [12 13 ... 
           ... 11 12]
     [13 10 11 12 13]]

In [32]:
import numpy as np
# 
a = np.arange(10, 14)
b = np.tile(a, 10)
b = b.reshape((8,5))
print(b)

[[10 11 12 13 10]
 [11 12 13 10 11]
 [12 13 10 11 12]
 [13 10 11 12 13]
 [10 11 12 13 10]
 [11 12 13 10 11]
 [12 13 10 11 12]
 [13 10 11 12 13]]


## Q9
Create a 4x6 array of ints.  Then create a new array with columns 2 and 4 of the original array swapped.

In [50]:
import numpy as np

a = np.arange(100,124).reshape(4,6)
print("Original array:")
print(a)

a[:,(2,4)] = a[:,(4,2)]
print("New array AFTER swapping")
print(a)

Original array:
[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]]
New array AFTER swapping
[[100 101 104 103 102 105]
 [106 107 110 109 108 111]
 [112 113 116 115 114 117]
 [118 119 122 121 120 123]]


## Q10
Create a 3x10 array.  Use the `rot90` method to rotate the array by 90 degrees.  Repeat this 4 times, so you get back
to the original array, printing the contents of the array on each step.

In [52]:
import numpy as np

a = np.arange(10, 40).reshape(3, 10)

a = np.rot90(a); print(f"STEP 1\n{a}"); print()
a = np.rot90(a); print(f"STEP 2\n{a}"); print()
a = np.rot90(a); print(f"STEP 3\n{a}"); print()
a = np.rot90(a); print(f"STEP 4\n{a}"); print()

STEP 1
[[19 29 39]
 [18 28 38]
 [17 27 37]
 [16 26 36]
 [15 25 35]
 [14 24 34]
 [13 23 33]
 [12 22 32]
 [11 21 31]
 [10 20 30]]

STEP 2
[[39 38 37 36 35 34 33 32 31 30]
 [29 28 27 26 25 24 23 22 21 20]
 [19 18 17 16 15 14 13 12 11 10]]

STEP 3
[[30 20 10]
 [31 21 11]
 [32 22 12]
 [33 23 13]
 [34 24 14]
 [35 25 15]
 [36 26 16]
 [37 27 17]
 [38 28 18]
 [39 29 19]]

STEP 4
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]



## Q11
Find the common elements of two 1D arrays below using the `intersect1d` method. 
<pre>
a = np.array([5,6,1,5,0,4,6,10,11,2,3])
b = np.array([6,2,10,9,4,9,3,2,1])
</pre>

In [53]:
import numpy as np

a = np.array([5,6,1,5,0,4,6,10,11,2,3])
b = np.array([6,2,10,9,4,9,3,2,1])

print(np.intersect1d(a,b))

[ 1  2  3  4  6 10]


## Q12
Create two 1D int arrays of equal size.  Then create a new array of the same size, selecting elements from the first array when the element in this array is even, and selecting elements from the second array 
when the element in the first array is odd.  
Use the following arrays as sample data:
<pre>
a = np.arange(10,50,3)
b = np.arange(100,114)
</pre>

In [36]:
import numpy as np

a = np.arange(10,50,3)
b = np.arange(100,114)

difference = np.where(a%2, a, b)
print(difference)


[100  13 102  19 104  25 106  31 108  37 110  43 112  49]


## Q13
Create a 4x6 array of random ints between 10 and 100.  Use the Numpy documentation to see what it means to define a masked array and then create a masked array where all values in the original array that are less than 50 are masked out.

In [54]:
import numpy as np
import numpy.ma as ma

a = np.random.randint(low=0, high=100, size=(4,6)); 
print(f"original array:\n{a}")

mask = ma.masked_array(a, mask=a<=50)
print(f"masked array:\n{mask}")

original array:
[[11  5 97  8  8 75]
 [80 29 12  9 59 90]
 [81 28 90  0 98 16]
 [22 39 32 38 50 76]]
masked array:
[[-- -- 97 -- -- 75]
 [80 -- -- -- 59 90]
 [81 -- 90 -- 98 --]
 [-- -- -- -- -- 76]]


## Q14
Create a 4x6 array of random ints between 10 and 100.  
Filter this array to produce a new 1D array consisting of only the numbers divisible by 3 in the original array.

In [55]:
import numpy as np

a = np.random.randint(low=10, high=100, size=(4,6))
b = a[a % 3 == 0]
print(f"original array:\n{a}")
print(f"filtered array:\n{b}") 

original array:
[[37 42 91 73 23 74]
 [48 24 76 14 14 85]
 [18 70 27 93 61 76]
 [65 15 30 43 89 96]]
filtered array:
[42 48 24 18 27 93 15 30 96]


## Q15
Create a 4x6 array of random ints between 10 and 100.  Then create a 4x6 array of indices of representing rankings of the first array.

For example the 2x3 array
<pre>
    [[49 56 61]
     [63 39 97]]
</pre>
yields the rankings
<pre>
    [[4 0 1]
     [2 3 5]]
</pre>

In [56]:
import numpy as np

shape = (4,6)
a = np.random.randint(low=10, high=100, size=shape)
print(f"a=\n{a}")
b = np.argsort(a, axis=None).reshape(shape)
print(f"b=\n{b}")

a=
[[60 37 20 30 87 42]
 [14 71 39 70 14 92]
 [61 67 99 35 57 77]
 [17 47 87 41 18 77]]
b=
[[ 6 10 18 22  2  3]
 [15  1  8 21  5 19]
 [16  0 12 13  9  7]
 [23 17 20  4 11 14]]


## Q16
Create a 1D array of random ints of size (30,) containing only the numbers 10, 11, 12, 13 or 14. Now create 30 'one hot encodings' for the original array.  You can read up about 'one hot encodings' on the web.  

For example a set of 'one hot encodings' for:
<pre>
    [20, 22, 21, 22, 20, 22]
</pre>
would be:
<pre>
    [1 0 0]
    [0 0 1]
    [0 1 0]
    [0 0 1]
    [1 0 0]
    [0 0 1]
</pre>

In [57]:
def one_hot_encodings(arr):
    unique = np.unique(arr)
    out = np.zeros((arr.shape[0], unique.shape[0]), dtype='int')
    for i, k in enumerate(arr):
        out[i, list(unique).index(k)] = 1
    return out

import numpy as np
a = np.random.randint(low=10, high=15, size=(30,)); print(a)
hot = one_hot_encodings(a)
print(hot)


[11 14 12 10 13 12 10 12 14 13 11 13 11 10 14 12 14 14 11 13 14 14 10 12
 12 12 14 14 12 12]
[[0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


## Q17
Create two vectors representing points in 3D space.  Now calculate the distance between these points.

In [58]:
import numpy as np

p1 = np.array([2.5, 4.1, 3.7])
p2 = np.array([5.5, 8.1, 8.7])

distance = np.sqrt(np.dot(p2-p1, p2-p1))
print(distance)

7.071067811865475


## Q18
Write a function that performs a 3D Cartesian to Spherical coordinate transformation on vectors.  Perform a Cartesian to Spherical coordinate transformation on each of
the Cartesian unit vectors:
<pre>
    iHat = [1, 0, 0]
    jHat = [0, 1, 0]
    kHat = [0, 0, 1]
</pre>
Note that the transfomation for kHat causes a singularity in Spherical coordinates, so try vectors very near kHat instead:
<pre>
    kHat_plus  = [+0.0001,0,1])
    kHat_minus = [-0.0001,0,1])
</pre>

In [45]:
import numpy as np
from numpy import sqrt, arccos
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})


def cartesianToSpherical(v):
    x, y, z = v
    r = sqrt(x**2 + y**2 + z**2)
    ϑ = arccos(z/r)
    𝜑 = arccos(x/sqrt(x**2+y**2))
    return np.array([r, ϑ, 𝜑])


iHat = np.array([1,0,0])
jHat = np.array([0,1,0])
kHat_plus  = np.array([+0.0001,0,1])
kHat_minus = np.array([-0.0001,0,1])
print( f"unit iHat = {cartesianToSpherical(iHat)}" )
print( f"unit jHat = {cartesianToSpherical(jHat)}" )
print( f"unit kHat+ = {cartesianToSpherical(kHat_plus)}" )
print( f"unit kHat- = {cartesianToSpherical(kHat_minus)}" )


unit iHat = [1.000 1.571 0.000]
unit jHat = [1.000 1.571 1.571]
unit kHat+ = [1.000 0.000 0.000]
unit kHat- = [1.000 0.000 3.142]
