# Numpy

In [12]:
# %load 01-creating-arrays.py
############################################################
#
#    creating arrays
#
############################################################

import numpy as np

np.set_printoptions(precision=3)

# create array filled with 1's
a = np.ones( (3,5) ); print(a)
b = np.ones( (3,5) ) * 13; print(b)

# create array filled with 0's
a = np.zeros( (3,5) ); print(a)

# create empty array
a = np.empty( (3,5), dtype=int); print(a) 

# create array from a list
a = np.array( [2,3,5,7,11,13,17] ); print(a)
a = np.array( [ [3,4],[5,6] ]); print(a)

# create array with random values
a = np.array( np.random.random((2,3)) ); print(a)

# create using arange
a = np.arange(4.0);      print(a)
a = np.arange(4.0,17.0);   print(a)
a = np.arange(4.0,6.0,0.1); print(a)

# create equally spaced arrays
a = np.linspace(-50.0,50.0,5); print(a)
a = np.linspace(-50.0,50.0,7); print(a)


1


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[13. 13. 13. 13. 13.]
 [13. 13. 13. 13. 13.]
 [13. 13. 13. 13. 13.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[ 2  3  5  7 11 13 17]
[[3 4]
 [5 6]]
[[0.063 0.105 0.985]
 [0.715 0.821 0.045]]
[0. 1. 2. 3.]
[ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
[4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7
 5.8 5.9]
[-50. -25.   0.  25.  50.]
[-50.    -33.333 -16.667   0.     16.667  33.333  50.   ]


1

In [13]:
# %load 02-reshaping-arrays.py
############################################################
#
#    reshaping arrays
#
############################################################

import numpy as np

# create array
a = np.arange(24); print(a)
# reshape it
b = a.reshape(2,3,4); print(b)
a[13] = 99
print(a)
print(b)
# display properties held in the view
print(type(b))
print("Shape:", b.shape)
print("Dimensions:", b.ndim)
print("Size:", b.size)
print("Item type:", b.dtype.name)
print("Item size:", b.itemsize)

1


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 99 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 99 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
<class 'numpy.ndarray'>
Shape: (2, 3, 4)
Dimensions: 3
Size: 24
Item type: int64
Item size: 8


1

In [14]:
# %load 03-vectorize-functions.py
import numpy as np
np.set_printoptions(precision=3)

# this only wors for scalars
def square(x): return x * x

# vectorize function to return floats
square2 = np.vectorize(square, otypes=[np.float])
x = np.arange(5, 10)
print(square2(x))         # now works for vectors
print(square2(10))        # but still works for scalars



[25. 36. 49. 64. 81.]
100.0


In [15]:
# %load 04-operating-on-arrays.py
############################################################
#
#    operating on arrays
#
############################################################

import numpy as np
np.set_printoptions(precision=3)


a = np.array( [3,3,3,3,4,3,3] )
b = np.array( [5,5,5,5,6,5,5] )

# operations are performed on each element
c = a * b + 2
print(c)


# dot and cross product
a = np.array( [[ 2,4], [3,5]] )
b = np.array( [[ 0,1], [1,0]] )
c = np.dot(a,b); print(c)
c = np.cross(a,b); print(c)
print()


1


[17 17 17 17 26 17 17]
[[4 2]
 [5 3]]
[ 2 -5]



1

In [ ]:
# %load 05-casting-numpy-arrays.py
import numpy as np
np.set_printoptions(precision=3)

# start with a float64 array
array1 = np.fromfunction(lambda i,j: (i+2)*(j+2)**1.4, (4,4))
print(array1.dtype)
print(array1)

# casting creates a new array of int
array2 = array1.astype(int)
print(array2.dtype)
print(array2)

# casting creates a new array of bool
array3 = array1.astype(bool)
print(array3.dtype) 
print(array3)


In [16]:
# %load 06-slicing-and-iterating.py
############################################################
#
#    slicing and iterating
#
############################################################

import numpy as np

# one dimensional arrays
a = np.arange(20); print(a)
print(a[7:14])
print(a[2:14:3])
print(a[::])
print()

# multi-dimensional arrays
a = np.arange(24).reshape(4,3,2); print(a)
print(a[0:2,0:2,0:2])



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 7  8  9 10 11 12 13]
[ 2  5  8 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[[0 1]
  [2 3]]

 [[6 7]
  [8 9]]]


In [17]:
# %load 07-stacking-arrays.py
############################################################
#
#    stacking arrays
#
############################################################

import numpy as np

a = np.ones( (3,5) ); print(a)
b = np.zeros( (3,5) ); print(b)

print("stacking")
h = np.hstack( (a,b) ); print(h)
v = np.vstack( (a,b) ); print(v)

1


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
stacking
[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


1

In [18]:
# %load 08A-broadcasting.py
############################################################
#
#    broadcasting
#
############################################################

import numpy as np

X = np.arange(1,7)
Y = np.arange(1,5)
print("X and Y are 1D arrays")
print(X)
print(Y)

Y = np.vstack(Y)
print("\nY is now a 2D array")
print(Y)
print("\nX is still a 1D array")
print(X)

print("\nbroadcast X and Y, because arrays are different sizes")
M = X * Y 
print(M)


1



X and Y are 1D arrays
[1 2 3 4 5 6]
[1 2 3 4]

Y is now a 2D array
[[1]
 [2]
 [3]
 [4]]

X is still a 1D array
[1 2 3 4 5 6]

broadcast X and Y, because arrays are different sizes
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]]


1

In [19]:
# %load 08B-broadcasting.py
############################################################
#
#    broadcasting
#
############################################################

import numpy as np
import matplotlib
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import axes3d, Axes3D

# a = [2, 4, 6, 8, 10]
a = np.arange(2, 10, 0.01)
x = np.hstack(a); print(x)
y = np.vstack(a); print(y)

f = y * np.cos(x)
# f = x * y
print(f)
fig = plt.figure()
ax = Axes3D(fig)
surface = ax.plot_surface(x, y, f, cmap="terrain", rstride = 25, cstride = 25) #, rstride=1, cstride=1, cmap=cmap, linewidth=0, antialiased=False)
plt.show()
1


[2.   2.01 2.02 2.03 2.04 2.05 2.06 2.07 2.08 2.09 2.1  2.11 2.12 2.13
 2.14 2.15 2.16 2.17 2.18 2.19 2.2  2.21 2.22 2.23 2.24 2.25 2.26 2.27
 2.28 2.29 2.3  2.31 2.32 2.33 2.34 2.35 2.36 2.37 2.38 2.39 2.4  2.41
 2.42 2.43 2.44 2.45 2.46 2.47 2.48 2.49 2.5  2.51 2.52 2.53 2.54 2.55
 2.56 2.57 2.58 2.59 2.6  2.61 2.62 2.63 2.64 2.65 2.66 2.67 2.68 2.69
 2.7  2.71 2.72 2.73 2.74 2.75 2.76 2.77 2.78 2.79 2.8  2.81 2.82 2.83
 2.84 2.85 2.86 2.87 2.88 2.89 2.9  2.91 2.92 2.93 2.94 2.95 2.96 2.97
 2.98 2.99 3.   3.01 3.02 3.03 3.04 3.05 3.06 3.07 3.08 3.09 3.1  3.11
 3.12 3.13 3.14 3.15 3.16 3.17 3.18 3.19 3.2  3.21 3.22 3.23 3.24 3.25
 3.26 3.27 3.28 3.29 3.3  3.31 3.32 3.33 3.34 3.35 3.36 3.37 3.38 3.39
 3.4  3.41 3.42 3.43 3.44 3.45 3.46 3.47 3.48 3.49 3.5  3.51 3.52 3.53
 3.54 3.55 3.56 3.57 3.58 3.59 3.6  3.61 3.62 3.63 3.64 3.65 3.66 3.67
 3.68 3.69 3.7  3.71 3.72 3.73 3.74 3.75 3.76 3.77 3.78 3.79 3.8  3.81
 3.82 3.83 3.84 3.85 3.86 3.87 3.88 3.89 3.9  3.91 3.92 3.93 3.94 3.95
 3.96 

<Figure size 640x480 with 1 Axes>

1

In [20]:
# %load 09-indexing.py
############################################################
#
#    indexing
#
############################################################

import numpy as np

# set up an array to be used in indexing
a = np.arange(10)**2; print(a)

# setup index arrays
index1 = np.array( [2,3,5,9] ); print(index1)
index2 = np.array( [[5,9],[2,3]]); print(index2)

# apply indexes to a
print(a[index1])
print(a[index2])

# set up a boolean filter for a
# filter is applied for each element of a; a is shortform of a[:,:]
a = np.arange(24).reshape(6,4); print(a)
filter = a % 3 == 0; print(filter)
a[filter] = 99; print(a)

filter = a[:,:] % 3 == 0; print(filter)
a[filter] = 88; print(a)



1



[ 0  1  4  9 16 25 36 49 64 81]
[2 3 5 9]
[[5 9]
 [2 3]]
[ 4  9 25 81]
[[25 81]
 [ 4  9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ True False False  True]
 [False False  True False]
 [False  True False False]
 [ True False False  True]
 [False False  True False]
 [False  True False False]]
[[99  1  2 99]
 [ 4  5 99  7]
 [ 8 99 10 11]
 [99 13 14 99]
 [16 17 99 19]
 [20 99 22 23]]
[[ True False False  True]
 [False False  True False]
 [False  True False False]
 [ True False False  True]
 [False False  True False]
 [False  True False False]]
[[88  1  2 88]
 [ 4  5 88  7]
 [ 8 88 10 11]
 [88 13 14 88]
 [16 17 88 19]
 [20 88 22 23]]


1

In [21]:
# %load 10-matrices.py
############################################################
#
#    matrices
#
############################################################

import numpy as np

# matrix multiplication (not element wise multiplication)
a = np.matrix( [[3,4,5],[2,3,8],[4,1,7]] ); print(a)
b = np.matrix( [[2,3,4],[1,2,7],[3,0,6]] ); print(b)
c = a * b; print(c)

a = np.matrix( [[3,5],[4,1]] ); print(a)
print("Transpose"); print(a.T)
print("Inverse"); print(a.I)
print("Determinate", np.linalg.det(a))
# linear algebra
# 5x + 3y = 31
# 2x - 7y = -45
# solution x=2, y=7
a = np.matrix( [[5,3],[2,-7]] )
v = np.matrix( [[31],[-45]] )
print(np.linalg.solve(a,v))

1



[[3 4 5]
 [2 3 8]
 [4 1 7]]
[[2 3 4]
 [1 2 7]
 [3 0 6]]
[[25 17 70]
 [31 12 77]
 [30 14 65]]
[[3 5]
 [4 1]]
Transpose
[[3 4]
 [5 1]]
Inverse
[[-0.059  0.294]
 [ 0.235 -0.176]]
Determinate -17.0
[[2.]
 [7.]]


1