In [4]:
# %load 01-creating-arrays.py
############################################################
#
#    creating arrays
#
############################################################

import numpy as np

np.set_printoptions(precision=3)

# create array filled with 1's
a = np.ones( (3,5) ); print(a)
b = np.ones( (3,5) ) * 13; print(b)

# create array filled with 0's
a = np.zeros( (3,5) ); print(a)

# create empty array
a = np.empty( (3,5), dtype=int); print(a) 

# create array from a list
a = np.array( [2,3,5,7,11,13,17] ); print(a)
a = np.array( [ [3,4],[5,6] ]); print(a)

# create array with random values
a = np.array( np.random.random((2,3)) ); print(a)

# create using arange
a = np.arange(4.0);      print(a)
a = np.arange(4.0,17.0);   print(a)
a = np.arange(4.0,6.0,0.1); print(a)

# create equally spaced arrays
a = np.linspace(-50.0,50.0,5); print(a)
a = np.linspace(-50.0,50.0,7); print(a)


1


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[13. 13. 13. 13. 13.]
 [13. 13. 13. 13. 13.]
 [13. 13. 13. 13. 13.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[ 2  3  5  7 11 13 17]
[[3 4]
 [5 6]]
[[0.937 0.641 0.798]
 [0.443 0.903 0.421]]
[0. 1. 2. 3.]
[ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
[4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7
 5.8 5.9]
[-50. -25.   0.  25.  50.]
[-50.    -33.333 -16.667   0.     16.667  33.333  50.   ]


1