<div style="color:red;background-color:black">
Diamond Light Source

<h1 style="color:red;background-color:antiquewhite"> Python Fundamentals: Nump</h1>  

©2000-20 Chris Seddon 
</div>

## 1
Execute the following cell to activate styling for this tutorial

In [1]:
from IPython.display import HTML
HTML(f"<style>{open('my.css').read()}</style>")

## 2
Numpy is a library that lets us work with multi-dimensional arrays.  

Most scientific analysis in Python uses Numpy.  Several libraries extend Numpy including Pandas (which is dealt with in a separate tutorial).

Let's begin by creating some Numpy arrays:

In [3]:
import numpy as np

np.set_printoptions(precision=3)

# create array filled with 1's
a = np.ones( (3,5) ); print(a)
b = np.ones( (3,5) ) * 13; print(b)

# create array filled with 0's
a = np.zeros( (3,5) ); print(a)

# create empty array of ints
a = np.empty( (3,5), dtype=int); print(a) 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[13. 13. 13. 13. 13.]
 [13. 13. 13. 13. 13.]
 [13. 13. 13. 13. 13.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


## 3
By default Numpy creates arrays of floats, but the last example shows how to work with arrays of int.  By the way, Numpy works with an internal precision of about 15 significant figures for floats, but the statement
<pre>np.set_printoptions(precision=3)</pre>
is just for rounding the printed output to 3 decimal places.  

Numpy arrays are different from ordinary Python lists or tuples.  Let's check the type of a Numpy array:

In [10]:
import numpy as np

a = np.ones( (3,5) )
print(type(a))

<class 'numpy.ndarray'>


## 4

All Numpy arrays are stored as 1 dimensional arrays, irrespective of their real dimensionality.  The data in the array is pointed at by a structure called the view which contains, amongst other things, this dimensionality information.

In the following example we create two Numpy arrays sharing the same set of data, but having different views.  The first array is created with "arange" and the second is a shallow copy of the first, but with its dimensionality changed using the "resize" function:

<img src="images/Slide9.jpg"/>


In [12]:
a = np.arange(24); print(a)
# reshape it
b = a.reshape(2,3,4); print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## 5
We can prove these two Numpy arrays share data by modifying one of the arrays - the other array sees the changes:

In [13]:
a[13] = 99
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 99 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 99 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## 6
And now for some more Numpy arrays ...

In [14]:
import numpy as np

# create array from a Python list
a = np.array( [2,3,5,7,11,13,17] ); print(a); print()
a = np.array( [ [3,4],[5,6] ]); print(a);  print()

# create array with random values
a = np.array( np.random.random((2,3)) ); print(a)

[ 2  3  5  7 11 13 17]

[[3 4]
 [5 6]]

[[0.688 0.389 0.341]
 [0.226 0.664 0.017]]


## 7


## 8


## 9


## 10


## 11


## 12


## 13


## 14


## 15


## 16


## 17


## 18


## 19


## 20
